name: Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.

      - run: deno fmt --check

      - run: deno lint

      - run: deno test --allow-write --allow-env --allow-sys --allow-read --allow-net --coverage=cov/

      - run: deno coverage --lcov cov/ > cov.lcov

      - name: Publish package
        run: deno publish --allow-dirty
